### ISSUE TITLE
Time is still reported incorreclty on Jenkins

### ISSUE THREAD

**Issue by manukall** [victorolinasc/junit-formatter#11]
Test execution times are still reported wrong in Jenkins in the latest version. I think that's because the single tests still have their time reported in milliseconds and Jenkins just sums up those times for the test suites.

**Comment by cs-victor-nascimento** [comment]
Ouch... I will apply the patch to individual tests too. Thanks for reporting. Will release 1.0.1 soon.

**Comment by cs-victor-nascimento** [comment]
Released 1.0.1 with the fix.

**Comment by manukall** [comment]
Wow, thanks for the quick fix!
