### ISSUE TITLE
Report XML file no longer generated

### ISSUE THREAD

**Issue by stevelove** [victorolinasc/junit-formatter#24]
After several months of working as expected, it seems junit-formatter is no longer generating the report file. If I lock the version down to either 1.0.0 or 1.0.1 in my mix.exs, the report is generated again and it works as expected. No other version seems to work. We're using the default options.

Apologies in advance for not having much to go on with this issue. I'll keep digging, but I wanted to see if anyone else has any ideas.

Here's a timeline of a few significant events in case it provides any clues, but I don't see any correlations:
Oct. 30, 2016 - junit-formatter 1.2.0
Nov. 7, 2016 - My project added junit-formatter
Feb. 9, 2017 - junit-formatter 1.3.0
Mar. 4, 2017 - My project upgraded to Erlang 19.2 and Elixir 1.4.2
Apr. 5, 2017 - junit-formatter no longer generating the XML results file

System:
Centos 7
Erlang 19.2
Elixir 1.4.2

I'll keep digging, but if anyone has any thoughts, I'd appreciate it.

**Comment by cs-victor-nascimento** [comment]
Hey @stevelove! Thanks for your report!

Can you provide some extra info? For example:

1 - What is your config for JUnitFormatter?
2 - Do you generate reports outside of the projects structure?
3 - Are you using multiple failures that were introduced in Elixir 1.2 (I am still waiting for feedback on #8)?
4 - What is your `test_helper.exs` config?

Regards,

**Comment by stevelove** [comment]
Thanks for the reply @cs-victor-nascimento, your question about the JUnitFormatter config helped me find a resolution.

We haven't been specifying any configuration because the defaults were acceptable to us. Out of curiosity, I simply added `config :junit_formatter, report_dir: "_build/test"` and now the report is generated as before, while using the latest version.

I'm happy to close the issue now, unless you'd like to keep it open to associate with any kind of fix.

**Comment by cs-victor-nascimento** [comment]
Hey @stevelove. Nice it worked. Will be closing the issue now. Feel free to re-open if you think it needs more discussing.

Cheers,
