### ISSUE TITLE
Feature Request: display file name and line number on failed tests

### ISSUE THREAD

**Issue by josephan** [victorolinasc/junit-formatter#36]
Hello, thank you for creating this library. What do you think about adding the file name and line number of a failed test?
If you see the failed test file and line number so you can run the specific test locally right away with:
`mix test test/some_test_file.exs:10`

JUnit formatter in CircleCI

Without file name and line number:
![Screen Shot 2019-11-19 at 7 24 58 PM](https://user-images.githubusercontent.com/8878596/69198426-a38d2d80-0b02-11ea-8bcb-577e3daa1894.png)

With file name and line number:
![Screen Shot 2019-11-19 at 7 24 47 PM](https://user-images.githubusercontent.com/8878596/69198432-a7b94b00-0b02-11ea-840e-2920770e4368.png)

**Comment by victorolinasc** [comment]
Hey @josephan ! Thanks for your request!

We have recently added the stacktrace pretty printed. In your example, if you open "more" you should probably see the file with line numbers in the stack trace as if it is shown in ex_unit. 

Does that help?

**Comment by josephan** [comment]
@victorolinasc ah you right, I didn't see that. Thanks for pointing that out 💯
