### ISSUE TITLE
Feature request: Automatic create report_dir

### ISSUE THREAD

**Issue by wingyplus** [victorolinasc/junit-formatter#43]
Currently, we need to create a directory specified in report_dir if it doesn't exists. So my proposal is try creating that directory before generating reports. 

Thoughts?

**Comment by wingyplus** [comment]
> Since it seems this is a very wanted feature perhaps we should just hide it in a very big warning + options. Not 100% sure about things here but generally I'd tend to walk the safest way. 

Do you mean we should introduce a new configuration for creating directory and warn them if it's set right?

**Comment by victorolinasc** [comment]
Yep! That is what I thought. PRs welcome! If nobody steps up I might focus on this later on.

**Comment by wingyplus** [comment]
@victorolinasc I prototype PR here https://github.com/victorolinasc/junit-formatter/pull/44. Feels free to comment.

**Comment by victorolinasc** [comment]
Sorry for the delay... I'll be looking into it this week. I was thinking about checking if the file already exists... but it is on my todo list :)

**Comment by wingyplus** [comment]
> Sorry for the delay... I'll be looking into it this week. I was thinking about checking if the file already exists... but it is on my todo list :)

I was thinking that we should cleanup report_dir before making a new one to make sure the report is correct result. What do you think?

**Comment by victorolinasc** [comment]
I think deleting files is always dangerous... that was the main issue about doing this in the first place =/

Imagine someone configures it badly and ends up deleting _build or deps or something even worse...

**Comment by wingyplus** [comment]
You're right. :)


So The only thing I can do with the PR might be check an error against mkdir_p and raise the error if it's not allow to create.
