### ISSUE TITLE
Skipped test stats not showing in generated junit XML report when using ExUnit >= 1.7.0

### ISSUE THREAD

**Issue by mengdaming** [victorolinasc/junit-formatter#49]
When running tests with some tests marked as skipped (using @tag :skip), these skipped tests don't show up in the generated junit XML test report.

I'm getting a report that looks like the following:

```xml
 <testsuite errors="0" failures="1" name="xxx" tests="2" time="...">
```

While I would expect to see somthing like this (with 1 test case marked as skipped):

```xml
<testsuite errors="0" failures="1" skipped="1" name="xxx" tests="3" time="...">
```

I did a bit of investigation and from what I could see ExUnit changed in version 1.7.0 their state type to use `:skipped` atom instead of `:skip` when marking skipped tests. Cf. the 2 links below:
- [ExUnit 1.6.6](https://hexdocs.pm/ex_unit/1.6.6/ExUnit.html#t:state/0)
- [ExUnit 1.7.0](https://hexdocs.pm/ex_unit/1.7.0/ExUnit.html#t:state/0)

So I guess updating [this line](https://github.com/victorolinasc/junit-formatter/blob/48004d12dad9abeab275d473c359121b78aece6f/lib/formatter.ex#L90) in junit-formatter could fix the problem. WDYT?

**Comment by victorolinasc** [comment]
We could add something like:

```elixir
def handle_cast({:test_finished, %ExUnit.Test{state: {tag, _}} = test}, config) when tag in [:skip, :skipped] do
```

PRs are most welcome!
