### ISSUE TITLE
No xml produced

### ISSUE THREAD

**Issue by ibizaman** [victorolinasc/junit-formatter#9]
I added `{:junit_formatter, "~>0.1.2"}` as a dependency, added `:junit_formatter` to the applications list and added `ExUnit.configure formatters: [JUnitFormatter, ExUnit.CLIFormatter]` before `ExUnit.start` but no xml file is produced.

I'm using elixir 1.2.2.
Did I miss something? What could I look to know what's going on?

**Comment by ibizaman** [comment]
eh my bad... I was looking in the wrong _build directory...

**Comment by cs-victor-nascimento** [comment]
No problem! If anything shows up just open a new Issue

**Comment by ibizaman** [comment]
I was looking in an app's _build folder that was a leftover from when umbrella apps did not share it.
